name: create TOC
# description: https://github.com/technote-space/toc-generator

# README.md:
# <!-- START doctoc -->
# <!-- END doctoc -->

run-name: create README table of contents by ${{ github.actor }}

on: 
  workflow_dispatch:
  push:
    paths:
      - './README.md'

permissions:
  contents: write

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: ./README.md
          FOLDING: false
